# Generated by Django 2.2 on 2020-04-08 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='end_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='下架时间'),
        ),
        migrations.AddField(
            model_name='banner',
            name='start_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='上架时间'),
        ),
    ]
