# Generated by Django 2.2 on 2020-04-08 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200408_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='link',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='轮播图广告地址'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='note',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='备注信息'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='orders',
            field=models.IntegerField(default=0, verbose_name='显示顺序'),
        ),
    ]
