# Generated by Django 2.2 on 2020-04-09 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200408_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nav',
            options={'verbose_name': '导航菜单', 'verbose_name_plural': '导航菜单'},
        ),
    ]
