# Generated by Django 2.2 on 2020-04-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthuser',
            name='name',
            field=models.CharField(blank=True, default='暂无', max_length=150, null=True, verbose_name='名称'),
        ),
    ]
