# Generated by Django 2.2 on 2020-04-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='html_content',
            field=models.TextField(blank=True, null=True, verbose_name='html内容'),
        ),
    ]
