# Generated by Django 2.2 on 2020-04-16 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20200416_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialmanager',
            name='special',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_list', to='article.Special', verbose_name='专题'),
        ),
        migrations.AlterField(
            model_name='specialmanager',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='special_list', to=settings.AUTH_USER_MODEL, verbose_name='管理员'),
        ),
    ]
