# Generated by Django 2.2 on 2020-04-16 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='暂无', help_text='用户昵称', max_length=20, null=True, unique=True, verbose_name='用户昵称'),
        ),
    ]
