# Generated by Django 2.2 on 2020-04-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200409_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='name',
            field=models.CharField(blank=True, default='暂无', max_length=150, null=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='nav',
            name='name',
            field=models.CharField(blank=True, default='暂无', max_length=150, null=True, verbose_name='名称'),
        ),
    ]
